apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-poc-loadr
  labels:
    app.wp.poc.loadr/name: wp-poc-loadr
spec:
  replicas: 3
  selector:
    matchLabels:
      app.wp.poc.loadr/name: wp-poc-loadr
  template:
    metadata:
      labels:
        app.wp.poc.loadr/name: wp-poc-loadr
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: kafka-topic-setup
          image: rhorv/kafka-adm:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "/tmp/kafka_2.13-2.8.0/bin/kafka-topics.sh --create --partitions 6 --if-not-exists --topic $${TOPIC_NAME} --bootstrap-server $${KAFKA_HOST}:$${KAFKA_PORT}" ]
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port
            - name: TOPIC_NAME
              value: "clearing-payment-t"
      containers:
        - name: wp-poc-loadr
          image: simonwfarrow/wp-poc-loadr:1.0.4
          imagePullPolicy: Always
          env:
            - name: TOPIC
              value: "clearing-payment-t"
            - name: CONCURRENCY
              value: "10"
            - name: PAYLOAD
              value: "{\"version\":1,\"@version\":\"1\",\"type\":\"business_events\",\"@timestamp\":\"TIMESTAMP\",\"id\":\"ID\",\"category\":\"event\",\"name\":\"payment_cleared\",\"payload\":{\"interchangeCostCurrency\":\"GBP\",\"interchangeCostAmount\":\"1\",\"scheme\":\"VISA\",\"id\":\"ID\",\"value\":\"10000\",\"currency\":\"GBP\",\"merchantId\":\"861edc23-ae0e-4a1d-84c8-c6aa98fb284e\",\"schemeFeeCurrency\":\"GBP\",\"schemeFeeAmount\":\"2\"},\"occurred_at\":\"TIMESTAMP\"}"
            - name: NUMEVENTS
              value: "100000"
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: port